### ISSUE TITLE
precondition failed but not sure why

### ISSUE THREAD

**Issue by sdellysse** [codemix/babel-plugin-contracts#12]
Hey there, I'm trying out this lib, and I have the following function:

```javascript
export const fib = (n) => {
  pre: {
    Number.isInteger(n);
    n > 0;
  }

  if (n === 0) {
    return 1;
  } else {
    return n + fib(n - 1);
  }

  post: {
    Number.isInteger(it);
    it > 0;
  }
};
```

when I run `fib(5)` I get `Error: Function  precondition failed: n > 0`

This shouldn't happen right?

Whole testbed is here: https://github.com/sdellysse/contract-test-n-zero

**Comment by symphoniasoftware** [comment]
Hi.
It's the recursivity. Your function will get called with `n` having the value `0` (because of `return n + fib(n - 1);`)
I would modify the precondition to `n >= 0;`

**Comment by sdellysse** [comment]
can't believe I missed that. Thanks!
