### ISSUE TITLE
special variable name

### ISSUE THREAD

**Issue by Mouvedia** [codemix/babel-plugin-contracts#5]
> Post-conditions introduce a special variable, `it` which refers to the result of the function.

Could you add a property—like `env`—that would let us use a custom variable name of our choosing?
cf https://github.com/codemix/babel-plugin-contracts/blob/feb3422d0b5bd8704a0cff6a5a26e28cb03353c9/src/index.js#L50

e.g.
```
{
  "pre": ""
  "post": ""
  "invariant": "",
  "it": ""
}

**Comment by phpnode** [comment]
released in v1.2.0

**Comment by Mouvedia** [comment]
@phpnode thanks.

BTW you could maybe add a blacklist containing reserved words.
e.g. `"names": { "invariant": "const" }`

**Comment by phpnode** [comment]
It'll fail the first time they run the code if the developer does something silly like that. That's warning enough :)

**Comment by Mouvedia** [comment]
I must be silly :)

I have opted for `"names": { "invariant": "persist" }` instead.
