### ISSUE TITLE
Var names are not customizable when using Webpack and Babel-loader plugin

### ISSUE THREAD

**Issue by njor** [codemix/babel-plugin-contracts#8]
Hello,
Thank you for this DBC library for JS.
I am encountering an issue with Webpack and Babel-loader plugin, where I set options to change the var names (for example "result" instead of "it"), but those are not used, and the default var names are used instead.
I have included a (basic) testcase.
Regards.

[testcase-babel-webpack.zip](https://github.com/codemix/babel-plugin-contracts/files/2152872/testcase-babel-webpack.zip)

**Comment by phpnode** [comment]
hi @njor sorry for the delay in getting back to you, this is happening because:

```json
["contracts", {
  "env": {
    "production": {
        "strip": true
    },
    "names": {
        "assert": "assert",
        "precondition": "before",
        "postcondition": "after",
        "invariant": "invariant",
        "return": "result",
        "old": "old"
    }
  }
}]
```

should be:

```json
["contracts", {
  "env": {
    "production": {
        "strip": true
    }
  },
  "names": {
      "assert": "assert",
      "precondition": "before",
      "postcondition": "after",
      "invariant": "invariant",
      "return": "result",
      "old": "old"
  }
}]
```

(the names are not an environment-specific setting)

**Comment by njor** [comment]
Oh, yes you are right, it works perfectly now. Thank you for your help and for your time.
Sorry about the false bug report.
